FROM confluentinc/cp-kafka-connect:latest
COPY /Users/Tatiana_Slednikova/Downloads/wepay-kafka-connect-bigquery-2.1.4 /usr/share/java/wepay-kafka-connect-bigquery-2.1.4
COPY /User/Tatiana_Slednikova/Downloads/
COPY /Users/Tatiana_Slednikova/gcp_cred/sa_onboardingproject_key.json /usr/share/java/
